environment:
  matrix:
  - julia_version: 0.7
  - julia_version: 1.0
  - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit  
branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "using Pkg;using Conda;isdir(Conda.ROOTENV)&&rm(Conda.ROOTENV, recursive=true);ENV[\"CONDA_JL_VERSION\"]=3;Pkg.build(\"Conda\");"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"