[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[CSV]]
deps = ["CategoricalArrays", "Compat", "DataFrames", "DataStreams", "Dates", "InternedStrings", "Missings", "Test", "WeakRefStrings"]
git-tree-sha1 = "9d62d3d577895a1e0b0bacd211a788be70127165"
uuid = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
version = "0.2.5"

[[CategoricalArrays]]
deps = ["Compat", "Future", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "903ab7490d404e313fc9bf53942e28b1ba9307e8"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.11"

[[CodecZlib]]
deps = ["BinaryProvider", "Compat", "Test", "TranscodingStreams"]
git-tree-sha1 = "82742ef572290f566c6fc6d977d87586a0d3d5f1"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.4.3"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "c478aec93ea90bb99c307a92df17a76131bf275f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.0.0"

[[Conda]]
deps = ["Compat", "JSON", "VersionParsing"]
git-tree-sha1 = "b76a441539d66a18ba34df28d34dc5b9202164a3"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.0.0"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Dates", "InteractiveUtils", "LinearAlgebra", "Missings", "Printf", "Random", "Reexport", "SortingAlgorithms", "Statistics", "StatsBase", "Test", "TranscodingStreams", "Unicode", "WeakRefStrings"]
git-tree-sha1 = "1cc9493d9b659db1fa6d584afc3f73d74341e567"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.12.0"

[[DataStreams]]
deps = ["Compat", "Missings", "NamedTuples", "WeakRefStrings"]
git-tree-sha1 = "62d1a39a3e9634eceb7413151b48cbc95521a059"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.3.6"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "a591110d3ac12c9b4d0cec163fcf234baed7f5ac"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.10.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[FileIO]]
deps = ["InteractiveUtils", "Pkg", "Random", "Test"]
git-tree-sha1 = "4cfe13dce8564c2d0b96ad4a3a7f99e05fb97d46"
uuid = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
version = "1.0.0"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[InternedStrings]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "ea877c3608e8468aebd899a6d610cba401186d73"
uuid = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
version = "0.6.2"

[[JLD2]]
deps = ["CodecZlib", "Compat", "DataStructures", "FileIO"]
git-tree-sha1 = "64d3ffd85e557a9e4afa9f256c1944ae7672bc80"
uuid = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
version = "0.0.6"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LearnBase]]
deps = ["Compat", "StatsBase"]
git-tree-sha1 = "3c2162fbf99b257907730c5e389df385896654a9"
uuid = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
version = "0.1.6"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LossFunctions]]
deps = ["LearnBase", "RecipesBase", "StatsBase"]
git-tree-sha1 = "49411b43c080d41a29119ce0b536b126eb59c9b0"
uuid = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
version = "0.2.0"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "18c17737f3d375b86b495144ba7ab359ab3dca57"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.2"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NamedTuples]]
git-tree-sha1 = "6374851ad4b15f2a20ac20637d38c550531fa684"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "4.0.2"

[[OnlineStats]]
deps = ["Compat", "DataStructures", "LearnBase", "LossFunctions", "NamedTuples", "OnlineStatsBase", "PenaltyFunctions", "RecipesBase", "Reexport", "StatsBase", "SweepOperator"]
git-tree-sha1 = "e3334879b3e0f892e6ec4d35341c5bcc69c80b99"
uuid = "a15396b6-48d5-5d58-9928-6d29437db91e"
version = "0.18.0"

[[OnlineStatsBase]]
deps = ["Compat", "LearnBase"]
git-tree-sha1 = "570bf35314e1be1f91be789794fe0436bb2d974d"
uuid = "925886fa-5bf2-5e8e-b522-a9147a512338"
version = "0.8.0"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "cc23c786049328c93138da14e7020a464d707a23"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "0.1.0"

[[PenaltyFunctions]]
deps = ["LearnBase", "RecipesBase"]
git-tree-sha1 = "998fb9e0cd0291e40f0423dcf044485511ad50f5"
uuid = "06bb1623-fdd5-5ca2-a01c-88eae3ea319e"
version = "0.0.2"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[ProgressMeter]]
deps = ["Compat"]
git-tree-sha1 = "30d3473425cdb13b23ff10dfc7727be8bcc2871a"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "0.5.6"

[[PyCall]]
deps = ["Compat", "Conda", "MacroTools", "VersionParsing"]
git-tree-sha1 = "dcb6e67213f812d75100cbf87e9c0fd6aebc01f5"
uuid = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
version = "1.17.1"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
deps = ["Random", "Test"]
git-tree-sha1 = "298e774bc0fd26b7011358fc9ff0223b4e81aaa6"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.4.0"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Revise]]
deps = ["Distributed", "FileWatching", "LibGit2", "OrderedCollections", "Pkg", "REPL", "Random", "Test", "Unicode"]
git-tree-sha1 = "d49990fc136cb88d5b48fb803bf5f44244e26b8d"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "0.5.4"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "70840f1a93da48bcc952e71b600f598532372eb0"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.0"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "515d9c751bc96f9680a2a19f76395ae8ac06a8f5"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.24.0"

[[SweepOperator]]
git-tree-sha1 = "3de8b7b1764431aea93f1dda464a4669879088d5"
uuid = "7522ee7d-7047-56d0-94d9-4bc626e7058d"
version = "0.1.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "d10e1e4b8fb8c6c50a1458c8e0de8f7abd0fc144"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.5.3"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "e8524bb636735227fd9d750dfa81f98db8bc5b0c"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.1"

[[WeakRefStrings]]
deps = ["Compat", "Missings"]
git-tree-sha1 = "bb0464e62baf3a0767340fbb51fed584159ad9b7"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.4.7"
