function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(Revise.parse_source!), Base.Dict{Module, Revise.ExprsSigs}, String, Module})
    precompile(Tuple{typeof(Revise.parse_source!), Base.Dict{Module, Revise.ExprsSigs}, String, Module})
    precompile(Tuple{typeof(Revise.process_parsed_files), Array{String, 1}})
    precompile(Tuple{typeof(Revise.process_parsed_files), Array{String, 1}})
    precompile(Tuple{typeof(Revise.watch_files_via_dir), String})
    precompile(Tuple{typeof(Revise.parse_source!), Base.Dict{Module, Revise.ExprsSigs}, String, Module})
    precompile(Tuple{typeof(Revise.process_parsed_files), Array{String, 1}})
    precompile(Tuple{typeof(Revise.watch_package), Base.PkgId})
    precompile(Tuple{typeof(Revise.watch_files_via_dir), String})
    precompile(Tuple{typeof(Revise.revise_dir_queued), String})
    precompile(Tuple{typeof(Revise.watch_files_via_dir), String})
    precompile(Tuple{typeof(Revise.systime)})
    precompile(Tuple{typeof(Revise.revise_dir_queued), String})
    precompile(Tuple{typeof(Revise.parse_pkg_files), Base.PkgId})
    precompile(Tuple{typeof(Revise.parse_pkg_files), Base.PkgId})
    precompile(Tuple{typeof(Revise.parse_pkg_files), Base.PkgId})
    precompile(Tuple{typeof(Revise.revise_dir_queued), String})
    precompile(Tuple{getfield(Revise, Symbol("##27#30")), Module, String})
    precompile(Tuple{getfield(Revise, Symbol("##10#12"))})
    precompile(Tuple{getfield(Revise, Symbol("##10#12"))})
    precompile(Tuple{getfield(Revise, Symbol("##10#12"))})
    precompile(Tuple{typeof(Revise.remove_from_included_files), Symbol})
    precompile(Tuple{getfield(Revise, Symbol("##27#30")), Module, String})
    precompile(Tuple{typeof(Revise._watch_package), Base.PkgId})
    precompile(Tuple{typeof(Revise._watch_package), Base.PkgId})
    precompile(Tuple{typeof(Revise._watch_package), Base.PkgId})
end
